### PR TITLE
[Issue230] Remove travis build for python 2.7 in .travis.yml

### PR DESCRIPTION
**Pull request by Didou09**
Fixes, in devel, Issue #230 

Travis will not build against python 2.7 anymore

### CODE REVIEW

**Comment by lasofivec** [comment]
Hi Didier,
Sorry but I feel this branch is a bit of a quick fix, when the branch [dedicated to dropping python 2](https://github.com/ToFuProject/tofu/tree/dropping-py2) seems more complete. Can we close this pull request ?

**Comment by Didou09** [comment]
You are right,
I had not seen the branch you mention, sorry
Closing

**Comment by Didou09** [comment]
tip : if possible try to stick with the Issue####_description naming convention for branches, it's the reason why I had not seen the branch dropping-py2

**Comment by Didou09** [comment]
You are right though, the other branch is way cleaner and more complete

**Pull request closed without merging**
