### PR TITLE
Bug was not there, but __repr__() now more robust in debug

### PR DESCRIPTION
**Pull request by Didou09**
Erratum
---------
The bug in `Rays._complete_dX12()` (see Issue #241) was not a bug: it was the input that was inappropriate (the line of sight geometry was not available in IDS). 
=> No change to Rays class

More informative camera construction from IDS
-----------------------------------------------------
A warning has been added to camera construction from ids if some channels have nan in D or u

General Improvement
---------------
I noticed that the overloading of the parent class ToFuObjectBase.__repr__() method, though very useful when everything works fine, was a problem when in debug mode inside a class because the debugger wants to print the current variables, including **_self_**. But while debugging inside the class, **_self_** is not fully valid yet and the get_summary() medthod may not work, leading to the debugger bugging...

The parent method __repr__() is now more robust in debug mode: falls back to __class__.__name__ if the current instance is not valid.

Issues
-------

Fixes, in devel, Issue #241

### CODE REVIEW

**Comment by lasofivec** [comment]
> ## Erratum
> 
> The bug in `Rays._complete_dX12()` (see Issue #241) was not a bug: it was the input that was inappropriate (the line of sight geometry was not available in IDS).
> => No change to Rays class

I'm confused as to why mention that in this PR ?
If the issue wasn't an issue, comment there and close it ?
And thus this PR doesn't solve the Issue as it wasn't an issue...

**Comment by Didou09** [comment]
Agreed, 
issue #241 commented and closed accordingly
This PR will simply serve as reference for it, but you are right, next time good practice would be to comment in issue and close it, since the PR doesn't change anything on this particular point

**Comment by Didou09** [comment]
agreed

**Comment by Didou09** [comment]
done

**Pull request merged**
