### PR TITLE
[doc] updated gallery tuto: bf #329

### PR DESCRIPTION
**Pull request by lasofivec**
Updated documentation as discussed in #329 

Results: https://tofuproject.github.io/tofu/auto_examples/tutorials/tuto_plot_gallery_fusion_machines.html#sphx-glr-auto-examples-tutorials-tuto-plot-gallery-fusion-machines-py

### CODE REVIEW

**Comment by lasofivec** [comment]
> Very good, however, I would leave this PR open until we have fixed Issue #331
> Because then we'll be able to add ASDEX Upgrade too in the tutorial :-)

Fine by me :)

> Until then, the png image for NSTX does not seem to show (at least on my web browser)

Fixed !

**Comment by Didou09** [comment]
> > Very good, however, I would leave this PR open until we have fixed Issue #331
> > Because then we'll be able to add ASDEX Upgrade too in the tutorial :-)
> 
> Fine by me :)

Now that PR #333  has been merged, could you also add AUG in the tutorial ? :-)

**Comment by lasofivec** [comment]
done

**Comment by Didou09** [comment]
Thanks !
I'm merging, ready for a release on Monday ?

**Pull request merged**
