### PR TITLE
Deploy test

### PR DESCRIPTION
**Pull request by lasofivec**
Solves #369

Includes not only `_updateversion.py` but also the cython headers files `*.pxd`:

- Corrections in `MANIFEST.in` (old `MANIFEST.txt`)
- Added _updateversion.py in setup file

### CODE REVIEW

**Comment by lasofivec** [comment]
I have, you can try with `pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tofu==1.4.3b3`

**Comment by lasofivec** [comment]
I have tried this on my machines as well and it's working. I feel like we have encounter this issue before with numpy incompatibilities. 
Could you try to uninstall and reinstall numpy in your environment ?

**Comment by Didou09** [comment]
I used python 3.6 in this environment, could it have something to do with it ? (instead of 3.7 ?)

But pip should automatically compile with the proper python no ?
Is it because of the pxd files that pip now wants 3.7 ?
Are they compulsory or can they be removed to keep pip install flexible ?

**Comment by Didou09** [comment]
I'm trying with fresh empty environment for 3.6 and one for 3.7, will tell you in a few minutes

**Comment by lasofivec** [comment]
No, the python version has nothing to do with it. 
If you encounter it again, try doing a `import numpy` and checking the version and file of numpy.
I think it's just a "dirty" installation.

**Comment by Didou09** [comment]
Hum,. looks like you are right, when I create a fresh empty environment with just python, and then install tofu with pip using the line you provided, ut works out of box (all dependencies handles and no bug) both for python 3.6 and 3.7   :-)

Great job ! 👍 

Do you feel we should investigate further this issue or we can close it ?

**Comment by lasofivec** [comment]
I think we can close it. It's a numpy/conda issue that we have encountered in the past.
Could you merge the branch ? :)

**Comment by Didou09** [comment]
I'll let you choose whether you want to delete the branch  
Great !

**Pull request merged**
