### PR TITLE
Issue756 flat crystal etendue

### PR DESCRIPTION
**Pull request by Didou09**
Main changes:
-------------------
* None, except a minor extra piece of copy-pasted code to help that kind of cases debugging 

Issues:
-----------
* Issue #756  was due to wrong input, no bug detected

Example:
------------

The outline of the crystal was provided such that the crystal was self-intersecting, resulting in reflected slit that was plummeting to 0 for central pixels

image

image
image

Indeed, the reflection of the slit on the crystal gradually disappears as we go from edge pixels to central pixels (index ii = 16)

image

A simple fix is to provide the outline in good order to avoid self-intersection of the polygon:
image

Which results in:

image

### CODE REVIEW

**Comment by cjperks7** [comment]
Thanks for catching my mistake! 

My one question is what's the quantity you're plotting in the bottom right of your last plot? Etendue? I wasn't able to reproduce it flipping through the options but may have missed something.

**Comment by Didou09** [comment]
> Thanks for catching my mistake!
> 
> My one question is what's the quantity you're plotting in the bottom right of your last plot? Etendue? I wasn't able to reproduce it flipping through the options but may have missed something.

Yes, it is the etendue, are you sure you loaded the good branch ?

**Comment by cjperks7** [comment]
Yeah, I think I am. I do `git checkout Issue756_FlatCrystalEtendue` and then run the minimum working example I passed to you yesterday with only this identified error. I'm getting an etendue of ~5e-14.

I'm interested in what's going on here because what you've plotted for etendue is more similar to what's come out for the von Hamos. I would expect to get numbers like that.

**Comment by cjperks7** [comment]
After checking, running the von Hamos with the same detector pixel settings (33,1) is giving ~1.3e-13 so comparing against the flat's ~5e-14 is only about a factor 3 difference. Not sure how your ~2e-12 for flat pops up, but like we talked about more careful signal comparison coming up since you hashed out these coding bits

**Comment by Didou09** [comment]
> After checking, running the von Hamos with the same detector pixel settings (33,1) is giving ~1.3e-13 so comparing against the flat's ~5e-14 is only about a factor 3 difference. Not sure how your ~2e-12 for flat pops up, but like we talked about more careful signal comparison coming up since you hashed out these coding bits

**Comment by Didou09** [comment]
OK, I got it, this 1e-12 etendue corresponds to the etendue without the rocking curve effects.
It's because after creating the PR I had shofted branches to a branch on which I had been temporarily deactivating the rocking curve , made the plots from there ((forgetting I had swithed branches).

So 5e-14 is the correct answer

**Comment by cjperks7** [comment]
> OK, I got it, this 1e-12 etendue corresponds to the etendue without the rocking curve effects. It's because after creating the PR I had shofted branches to a branch on which I had been temporarily deactivating the rocking curve , made the plots from there ((forgetting I had swithed branches).
> 
> So 5e-14 is the correct answer

Damn, yeah that checks out. I can recover this plot turning off the rocking curve

**Comment by cjperks7** [comment]
Always helps to test our understanding of the numbers. Yeah, I think everything's good here

**Pull request merged**
