### PR TITLE
Issue654 rocking curve germanium

### PR DESCRIPTION
**Pull request by cjperks7**
### Changes
- Rocking curves for Germanium crystals can now be used
   - The computation has been benchmarked against the x0h online service to good agreement
   - https://x-server.gmca.aps.anl.gov/cgi/www_form.exe?template=x0h_form.htm
   - Both codes use the same dynamical diffraction theory so differences really amount to the input data for atomic scattering factors used
   - For Ge, the data for the anomalous contribution (impacts peaking) was obtained from NIST X-ray Form Factor, Attenuation, and Scattering Tables which is a different source than what's been implemented for Quartz. The same source was used for the mean contribution (impacts width)
   - https://physics.nist.gov/PhysRefData/FFast/html/form.html
   - Screenshot 2023-06-30 at 1 51 03 PM
   - Screenshot 2023-06-30 at 1 51 28 PM

- Generalized function input to allow for arbitrary Miller indices
    - This is useful for arbitrarily scoping crystal cuts (hence Bragg angle) v. integrated reflectivity for a reference wavelength
    - Screenshot 2023-06-30 at 1 51 46 PM

### Minimum working code
- If one wants to directly utilize the rocking curve computation function
```
# Modules
import tofu.spectro._rockingcurve as rc

# C-Mod's crystal
dcry2 = {
    'material': 'Quartz',
    'name': 'HIREX',
    'symbol': 'Qz102',
    'miller': np.r_[1., 0., 2.,],
    'target': {
        'ion': 'Ar16+',
        'lamb': 3.96, 
        'units': 'AA',
        },
    'd_hkl': None,
    }

# Computes rocking curve
dout2 = rc.compute_rockingcurve(
    crystal = dcry2['name'], 
    din=dcry2, 
    lamb = dcry2['target']['lamb'], 
    plot_power_ratio = True
    )
```

 - If one is building a crystal spectrometer using the ToFu Collection object
     - NOTE: One quirk I noticed is that you have to define d_hkl to be >0 float in the dmat dictionary even though what you put isn't used and instead d_hkl is recalculated using the Miller index. You might as well know it so I haven't changed this
```
# Collection object
import tofu as tf
coll = tf.data.Collection()

# Defines diffraction object
dcry ={
    # Defines crystal geometry
    'dgeom': {
        'cent': np.array([1,1,1]), # [m], center in global axis
        'nin': np.array([1,0,0]), # inward normal vec
        'e0': np.array([0,1,0]), # horizontal vec
        'e1': np.array([0,0,1]), # vertical vec
        'curve_r': np.array([1385e-3, 1385e-3]), # [m], crystal radius of curvature
        'extenthalf': np.array([64e-3/2, 27e-3/2]), # [m], disp. of corners wrt cent in (hor. ver.)
    },
    # Defines crystal material
    'dmat': {
        'material': 'Quartz',
        'name': 'HIREX',
        'symbol': 'Qz102',
        'miller': np.r_[1., 0., 2.],
        'target':{
            'ion': 'Ar16+',
            'lamb': 3.96, # [1e-10 m], photon wavelength
            'units': 'AA',
            }, 
        'd_hkl': 2.281124272650091, # [m], crystal lattice spacing
        },
    }

# Adds diffraction crystal object to diagnostic
coll.add_crystal(
    key='cry',
    dgeom=dcry['dgeom'],
    dmat=dcry['dmat'],
    )
```

### If a crystal is ever added again in the future for whatever reason
- If I didn't spend time learning the theory or learning & reorganizing the code, it could have been ~day effort to add data for a new crystal material
   - What you'll need is:
   - Knowledge on the crystal structure -> atom positions, inter-atomic distances, crystal shape
   - Source -- R.W.G. Wyckoff, Crystal Structures (1963)
   - Thermal conductivity
   - Source -- basically Googled it
   - Atomic Scattering Factors
   - Source -- (mean) Int. Tab. X-Ray Crystallography, Vol.I,II,III,IV (1985), Table 3.3.1A; (anomalous) NIST X-ray Form Factor, Attenuation, and Scattering Tables

### CODE REVIEW

**Comment by cjperks7** [comment]
@Didou09 I closed my last PR and then opened this one hoping turning on/off would fix things, but seems like the last commit which ran through the checks just fine once is now experiencing a new "_tkinter.TclError" in I think a different spot.... Not sure what's going on

**Comment by cjperks7** [comment]
Converted to draft. Had a conversation with Adrien were they informed me of the reference for their atomic scattering factors. Going to switch out the data tables for Ge and update references

**Comment by Didou09** [comment]
well done @cjperks7 !

That's a really great new feature !

Will wait until you reconvert this to ready for review

As for that  "_tkinter.TclError", this is typical of when Github did not install TKinter correctly, so nothing to be blamed on your code. 

Easy fix when it happens: just rerun the unit tests using that top right buttons:

image

**Comment by cjperks7** [comment]
> y fix when it happens: just rerun the unit tests using that top right buttons:

I was thinking there had to be something like that, but couldn't find it. Thanks for the help!

**Comment by cjperks7** [comment]
@Didou09 There PR sound be ready now. I switched out the data table source and surprise, surprise nothing changed. The sources give almost the exact same curves

**Review by Didou09 — APPROVED** [review]
well done

**Comment by Didou09** [comment]
@cjperks7 , could you add here also the minimum working code for reproducing the all-miller cuts plot for Ge and Quartz at desired wavelength ?

**Comment by cjperks7** [comment]
> could you add here also the minimum working code for reproducing the all-miller cuts plot for Ge and Quartz at

```
###########################################################
#
#           Scope over integrated reflectivity
#
###########################################################

from scipy.interpolate import interp1d
import tofu.spectro._rockingcurve as rc

miller_max = 10

ddd = int(miller_max+1)

fig2, ax2 = plt.subplots()


# Loop over materials
for mat in ['Quartz', 'Germanium']:
    results = {
        'Bragg': np.zeros((ddd,ddd, ddd)),
        'Rint':  np.zeros((ddd,ddd, ddd)),
        'miller': np.full((ddd,ddd,ddd), 'hkl', dtype='S3')
    }

    # Loop over Miller indices
    for hh in np.arange(miller_max+1):
        for kk in np.arange(miller_max+1):
            for ll in np.arange(miller_max+1):

                # skip bulk reflection
                if hh==0 and kk==0 and ll==0:
                    continue

                # Builds material matrix
                dcry4 = {
                    'material': mat,
                    'name': 'SCOPING',
                    'symbol': mat[:2]+str(hh)+str(kk)+str(ll),
                    'miller': np.r_[hh, kk, ll,],
                    'target': {
                        'ion': 'Kr34+',
                        'lamb': 0.944, # e-10
                        #'lamb': 2.72,
                        'units': 'A',
                        },
                    'd_hkl': None,
                    }

                results['miller'][hh,kk,ll] = str(hh)+str(kk)+str(ll)

                # Calculates rocking curve
                try:
                    dout4 = rc.compute_rockingcurve(
                        crystal = dcry4['name'],
                        din=dcry4,
                        lamb = dcry4['target']['lamb'], 
                        plot_power_ratio = False
                        )

                    results['Bragg'][hh,kk,ll] = dout4['Bragg angle of reference (rad)']*180/np.pi

                    results['Rint'][hh,kk,ll] = np.trapz(
                            np.nanmean(
                                [
                                    dout['Power ratio'][0,0,0,:],
                                    interp1d(
                                        dout['Glancing angles'][1,0,0,:],
                                        dout['Power ratio'][1,0,0,:],
                                        bounds_error=False,
                                        fill_value = (
                                            dout['Power ratio'][1,0,0,0],
                                            dout['Power ratio'][1,0,0,-1]
                                            )
                                        )(dout['Glancing angles'][0,0,0,:])
                                    ],
                                axis=0
                                ),
                            dout['Glancing angles'][0,0,0,:]
                            )

                except:
                    blha=0

                
    ax2.plot(
        results['Bragg'].flatten(),
        results['Rint'].flatten(),
        '*',
        label = mat
        )

ax2.set_xlabel(r'$\theta_B$ [deg]')
ax2.set_ylabel('Integrated refelctivity [rad]')
ax2.set_title(r'$\lambda=$'+str(dcry4['target']['lamb'])+r'$\AA$')
ax2.set_yscale('log')
ax2.grid('on')
ax2.legend()




```

**Comment by Didou09** [comment]
@cjperks7 , running this MWE as such  I get an empty figure.

Looks like every iteration of the nested loop falls into an exception, which is handled by the try/except statement.

Removing the try/except to print the exception I get:


image

**Comment by Didou09** [comment]
So, looks like for some miller indices it's normal that there is no solution.
For others, the error came from a typo: `dout` is called instead of `dout4` (`dout` is not declared).

Replacing dout by dout4 in the innner loops solves the problem for Germanium.

**Comment by cjperks7** [comment]
> So, looks like for some miller indices it's normal that there is no solution.

Those crashes you're seeing are for physics reasons. You're in a situation where lambda/2d >1 so sin\theta_B is undefined. `psi_re` specifically causes the crash because it, after a few steps of math, stems from a data table interpolated on a grid of sin\theta_B /lambda so undefined. So the point is that cut pairing won't reflect.

Another physics reason for a different type of crash I've seen for Quartz (and I'm pretty sure can't happen for Germanium, I haven't verified the math), but there's some Miller indices where due to the crystalline structure only destructive interference is possible

I have taken the time to benchmark the integrated reflectivity v. Bragg angle scope plot going through all the Germanium cuts for He-like Kr and Ne-like Xe and can attest that every cut you'd expect to have present on the plot is there.

I just haven't attempted to use a more sophisticated filtering for bad cut parings beyond the try/except. Sometimes there's a cut with one really high Miller index, i.e. (515), with a bunch of low ones that'd have a valid Bragg angle so that's why I made the loop go over so many invalid cuts with all really high Miller indices, i.e. (555). It's all so the plot would have a good density of points.

**Comment by cjperks7** [comment]
> om a typo: `dout` is called instead of `dout4` (`dout` is not declared).

Sorry about that! That's probably a relic from my just pulling that MWE out of the middle of a scratch script I was using

**Pull request merged**
