### PR TITLE
Issue281 new default configs

### PR DESCRIPTION
**Pull request by Didou09**
Added more details to the default ITER geometry:
* Central solenoid coils
* Poloidal field coils
* Inner and outer vessel
* Cryostat

All data was taken from imas ids:
ids=['wall', 'pf_active'],shot=1180, run=17, tokamak='ITER_MD', user='public'

image

### CODE REVIEW

**Comment by Didou09** [comment]
@lasofivec , all travis tests are passing for this PR, but 1 GA is failing, it seems to have something to do with compilation ?

**Comment by lasofivec** [comment]
it seems to be a real bug

**Comment by lasofivec** [comment]
it seems to be related to this 
https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

**Comment by Didou09** [comment]
Hum... but the error message has very little information, and the link you proposed mentions it seems to be related to an issue with the numpy installation... maybe rerunning the test would solve it ?

**Comment by Didou09** [comment]
I reran the test, it failed again with the same error

**Comment by lasofivec** [comment]
Take a look at this gigantic thread: https://github.com/scikit-learn-contrib/hdbscan/issues/457#issuecomment-773671043

**Comment by lasofivec** [comment]
i'm testing something on a patch branch

**Comment by lasofivec** [comment]
See #461

**Comment by Didou09** [comment]
Merged with devel to push the changes implemented by #461 into this branch to make sure the tests don't fail

**Pull request merged**
