### PR TITLE
#Issue272 Cythonvscython

### PR DESCRIPTION
**Pull request by Didou09**
Fixes, in devel, issue #272 to make pip install easier

### CODE REVIEW

**Comment by lasofivec** [comment]
I'm not sure this would work...
I opened a new branch yesterday

**Comment by lasofivec** [comment]
I wouldn't change the Cython/cython if they were not the issue in the first place... what do you think @Didou09

**Comment by lasofivec** [comment]
https://luminousmen.com/post/resolve-cython-and-numpy-dependencies

**Comment by Didou09** [comment]
Fall back to a more generic and modern solution as recommended in setuptools's answer to the opened issue (see few last comments on Issue #272 )

Closing the PR as we are changing solution

**Comment by Didou09** [comment]
Sorry, should have merged this before closing, there are still interesting changes (try / except + setup_requires) that can be useful.

**Comment by Didou09** [comment]
To be clairifie din teh future branch : are the changes implemented here (try / except func + setup_requires) still useful / necessary even with te toml file ?

**Pull request merged**
