### PR TITLE
Deploy test

### PR DESCRIPTION
**Pull request by lasofivec**
This PR should fix a couple of issues:

- Issue #340 :  _The version number in tofu/version.py had to be forced by hand_
  The problem came from the fact that travis checkouts the tag commit of tofu so the repository is not a specific branch but on a detached HEAD. I changed the `setup.py` so that it checks if it is building a travis tag version (by checking if `$TRAVIS_TAG` exists)
 https://github.com/ToFuProject/tofu/blob/d16595dbca1bc8b516f03abced987c3c2fa2f460/setup.py#L168-L169

- Issue #340 : _Apparently the deployment was also done on test-pypi_
As I mentioned in the issue, the condition `on: tags: True` sets TRAVIS_BRANCH to the tag number, thus it is no longer `master` nor `deploy-test` (nor any other branch name).
Solved this by checking to which git branch the commit hash corresponds to:

https://github.com/ToFuProject/tofu/blob/d16595dbca1bc8b516f03abced987c3c2fa2f460/.travis.yml#L64-L65

and then checking the result as a condition for deployment

https://github.com/ToFuProject/tofu/blob/d16595dbca1bc8b516f03abced987c3c2fa2f460/.travis.yml#L96

There is one caveat for this to work properly, that should still be the proper way to release (will update the documentation):
It is necessary to first push the commit and then push the tag (if you only push the tag it will not find a branch corresponding to that tag so there will be no deployment). Thus, the workflow for a release should be something similar to:

```
# make changes
pip install -e .[dev] # check that it builds
nosetest # check that nothing is broken
git commit -m " some commit message"
git tag -a x.y.z -m "some tag comment"
git push origin
git push --tags
```

- Even if anaconda deployment was not being done, the recipe was still being build. which makes the whole process for nothing, so now it is being done in the upload script

- Issue #292 : the file `_updateversion.py` was no longer being deployed with pip:
https://github.com/ToFuProject/tofu/issues/292#issuecomment-582427149
I used the second solution: I took out out `build-backend = "setuptools.build_meta"` in `pyproject.toml`

### CODE REVIEW

**Comment by lasofivec** [comment]
If you agree with these changes, I would add them to release 1.4.2, what do you think ?

**Comment by lasofivec** [comment]
is it ok with you if I try adding this to `master`(v 1.4.2) directly ?

**Comment by Didou09** [comment]
Since we have several PR to merge to master, I suggest we redo a release of 1.4.2 (delete the tag, retag, re-deploy) through a proper PR from devel to master.

I would just like to solve issue #346 before that, hopefully this afternoon, ok for you ?
It's not very clean (deleting tags, retagging...) but we are tuning our release worflow and it shoud get cleaner in the future.

Or, we can start now a cleaner workflow:
* From now on when we do an important release (new major features like the volumes of sight, solid angles...) we increment the second number (1.5.0)
* For all minor features, small improvements, debugging, we increment the third number (1.4.2 => 1.4.3)
* So we could start this afternoon by tagging 1.4.3 instead of deleting 1.4.2

What do you think ?

**Comment by lasofivec** [comment]
Sounds good to me :)

**Pull request merged**
