### PR TITLE
update doc as of 2022

### PR DESCRIPTION
**Pull request by flothesof**
As discussed at the end of https://github.com/ToFuProject/tofu/issues/599#issuecomment-990032743, here is a small review and improvement of the docs regarding mostly installation.

Notable changes to doc:
- removed specialized instructions in favor of conda-forge for normal users: I believe it’s simpler to advertise this "one size fits all solution" rather than the previous version
- rewrote developer install and made sure it works on my machine
- better links to other parts of the doc

Possible improvements I saw while working on this:
- the "normal" tests took 11 minutes to complete, this is really crazy since they took less than 2 minutes a couple of months ago --> this is something that will probably deter contributors
- I don’t understand the "how to construct the doc" section https://tofuproject.github.io/tofu/dev_tutos.html#how-to-construct-the-doc, in my opinion it would be worth reworking @lasofivec what do you think?
- I haven’t checked the README, it would probably be a good idea to check it for coherence with these install instructions

@Didou09 @lasofivec what do you think?

### CODE REVIEW

**Review by Didou09 — APPROVED** [review]
I am ok with this PR, thanks you @flothesof

**Comment by Didou09** [comment]
On the additional thougts:
* **tests duration:** I agree 11 minutes is bit too long, will try to reduce that (2 commits in PR # already address it partially, but more can probably be done in the near-future)
* **how to construct the doc:** I'll try to go through it again
* **README**: will try to go through it before the next release


Thanks !

**Comment by lasofivec** [comment]
> I don’t understand the "how to construct the doc" section https://tofuproject.github.io/tofu/dev_tutos.html#how-to-construct-the-doc, in my opinion it would be worth reworking @lasofivec what do you think?

Hi Flo, we went over it not so long ago with Didier. What did you find confusing? Could you elaborate on that?

**Comment by flothesof** [comment]
@lasofivec Sure: 
- the title says "how to construct the doc" but the content describes two things: building + uploading to GH (if I understand correctly)
- I don’t understand why a two repo solution is needed (in my experience, I can build the doc in the tofu directory), I find it rather confusing (but see above point: maybe I misunderstood the goal of the section)
- under windows I couldn’t get make html working (and ran the build with sphinx-build instead)

**Pull request merged**
